#!/usr/bin/env python3
"""Compile the path-only SVG artwork into Android vectors (Python stdlib only)."""
from pathlib import Path
import argparse
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SVG = '{http://www.w3.org/2000/svg}'
ANDROID = 'http://schemas.android.com/apk/res/android'
AAPT = 'http://schemas.android.com/aapt'
ET.register_namespace('android', ANDROID)
ET.register_namespace('aapt', AAPT)

def attrs(**values):
    return {f'{{{ANDROID}}}{key}': str(value) for key, value in values.items()}


def vector(paths, gradients, *, size=108, viewport=108, translate=None, clip=None):
    result = ET.Element('vector', attrs(width=f'{size}dp', height=f'{size}dp',
        viewportWidth=viewport, viewportHeight=viewport))
    parent = result
    if translate:
        parent = ET.SubElement(result, 'group', attrs(translateX=translate[0], translateY=translate[1]))
    if clip:
        ET.SubElement(parent, 'clip-path', attrs(pathData=clip))
    for source in paths:
        if source.tag != SVG + 'path':
            raise ValueError('Artwork layers must contain only paths')
        unsupported = set(source.attrib) - {'d', 'fill', 'fill-opacity', 'fill-rule'}
        if unsupported:
            raise ValueError(f'Unsupported SVG attributes: {unsupported}')
        fill = source.get('fill', '#000000')
        path = ET.SubElement(parent, 'path', attrs(pathData=source.attrib['d'],
            fillAlpha=source.get('fill-opacity', '1'),
            fillType='evenOdd' if source.get('fill-rule') == 'evenodd' else 'nonZero'))
        if not fill.startswith('url(#'):
            path.set(f'{{{ANDROID}}}fillColor', fill)
            continue
        gradient = gradients[fill[5:-1]]
        resource = ET.SubElement(path, f'{{{AAPT}}}attr', {'name': 'android:fillColor'})
        compiled = ET.SubElement(resource, 'gradient', attrs(type='linear',
            startX=gradient.attrib['x1'], startY=gradient.attrib['y1'],
            endX=gradient.attrib['x2'], endY=gradient.attrib['y2']))
        for stop in gradient:
            ET.SubElement(compiled, 'item', attrs(offset=stop.attrib['offset'],
                color=stop.attrib['stop-color']))
    return result


def generate():
    svg = ET.parse(ROOT / 'artwork/icon.svg').getroot()
    gradients = {g.attrib['id']: g for g in svg.iter(SVG + 'linearGradient')}
    layers = {g.attrib['id']: list(g) for g in svg.iter(SVG + 'g') if 'id' in g.attrib}
    mono = list(ET.parse(ROOT / 'artwork/icon-monochrome.svg').getroot())
    outputs = {
        'drawable/ic_launcher_background.xml': vector(layers['background'], gradients),
        'drawable/ic_launcher_foreground.xml': vector(layers['foreground'], gradients),
        'drawable/ic_launcher_monochrome.xml': vector(mono, {}),
        'mipmap-anydpi/ic_launcher.xml': vector(layers['background'] + layers['foreground'],
            gradients, size=48, viewport=72, translate=(-18, -18), clip=
            'M40 18H68Q90 18 90 40V68Q90 90 68 90H40Q18 90 18 68V40Q18 18 40 18Z'),
    }
    for api in (26, 33):
        adaptive = ET.Element('adaptive-icon')
        for layer in ('background', 'foreground') + (('monochrome',) if api == 33 else ()):
            ET.SubElement(adaptive, layer, attrs(drawable=f'@drawable/ic_launcher_{layer}'))
        outputs[f'mipmap-anydpi-v{api}/ic_launcher.xml'] = adaptive
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail if committed vectors differ from SVG')
    args = parser.parse_args()
    for name, element in generate().items():
        ET.indent(element, space='    ')
        text = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/generate-icons.py; edit artwork/*.svg. -->\n' + ET.tostring(element, encoding='unicode') + '\n'
        path = ROOT / 'res' / name
        if args.check:
            if not path.exists() or path.read_text() != text:
                raise SystemExit(f'Out of date: {path}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    print('SVG / Android vectors are in sync' if args.check else 'Generated Android icon resources')


if __name__ == '__main__':
    main()
